-- Set the colors for Tabline
-- highlight(0, "BufferDefaultVisible", { ctermfg = 20 })
-- highlight(0, "BufferDefaultInactive", { ctermfg = 20 })
-- highlight(0, "BufferDefaultCurrent", { ctermfg = 'white', ctermbg = 'black' })
-- vim.cmd([[highlight BufferDefaultCurrent ctermfg=white ctermbg=black]])
